<template>

  <div class="wrapper">

    <div class="container">
      
      <div class="header">

        <div class="logo-wrapper">

          <img class="hs-logo" src="./assets/hs-logo.png">

          <span class="hs-words">Hearthstone Book</span>
          

        </div> <!-- logo-wrapper -->

      </div> <!-- header -->

      <div id="card-loader-text" ref="cardLoaderTextDiv" v-html="cardLoaderText"></div>

      <div class="classes-wrapper">

        <div class="classes-grid">

          <div class="my-class" v-for="myClass in classes" :key="myClass.class" @click="setClassFilter(myClass.class)" :class="(cardClassFilter[0] == myClass.class && cardClassFilter.length == 1 || cardClassFilter.length > 1) ? 'active-class' : ''">

            <h1 class="class-name">
              {{ myClass.class }}
            </h1>

            <img class="class-image" :src="myClass.img">

          </div>

        </div> <!-- classes-grid -->

      </div> <!-- classes-wrapper -->

      <div class="header-container">

        <costs @select="selectCost" :currentCost="viewingCost"/>

      </div> <!-- header-container -->

      <div class="center-container">

        <div class="travel-buttons-container">

          <div class="travel-buttons button-left" @click="cycleBack">

            &#8592;

          </div>	

        </div> <!-- travel-buttons-container -->

        <div class="card-container">

          <div class="card-item" v-for="(_card, $index) in cards" :key="$index">

            <Card :card="_card" :updatePage="updatePage"/>

          </div>

        </div> <!-- card-container -->
        
        <div class="travel-buttons-container">

          <div class="travel-buttons button-right" @click="cycleForward">

            &#8594;

          </div>

        </div> <!-- travel-buttons-container -->

      </div> <!-- center-container -->

      <div class="expansion-container">

        <h1>Filter by Card Set</h1>

        <div class="expansion" v-for="(myExpansion, $index) in HEARTHSTONE_CARD_SEGMENTS" :key="$index">

          <span>
            <input type="checkbox" class="expansion-checkbox" :expansion="myExpansion" @click="toggleExpansionFilter(myExpansion)" :checked="cardExpansionFilter.indexOf(myExpansion) != -1">
            <span>{{ myExpansion }}</span>
          </span>

        </div>

      </div> <!-- expansion-container -->

      <div class="footer-wrapper">

        <p class="disclaminer">
          All assets owned by <a target="_blank" href="https://www.blizzard.com/en-us/" title="Blizzard Entertainment website"> Blizzard Entertainment</a>. 
          Card data generated by <a target="_blank" href="https://hearthstoneapi.com/" title="Heartstone API website">Heartstone API</a>.
        </p>

      </div> <!-- footer-wrapper -->


    </div> <!-- container -->

  </div> <!-- wrapper -->
</template>

<script>

import Costs from './components/Costs.vue'
import Card from "./components/Card.vue"

function cl(_message, ...args) {
  console.log(_message)

  if(args.length > 0) {
    for(let _i in args) {
      console.log(_i)
    }
  }
}

export default {

  components: {
    Card,
    Costs
  },

  mounted() { 
    this.init()
  },

  data() {

    return {

      apiBase: "https://omgvamp-hearthstone-v1.p.mashape.com/cards",
      apiKey: "aDmChYvfeCmshJkIxNzZ7TovY5Fvp1LgcFijsnQl8wojcuVxGD",

      updatePage: 0,

      asyncDataInTransit: false,
    
      // Collection of card costs currently being viewed
      viewingCost: 1,

      cardLoaderText: "<p style='color: red; text-align: center; margin-bottom: 20px; '>Loading card data...</p>",

      classes: [

        {
          class: "Druid",
          img: require("./assets/" + "Druid.png")
        },

        {
          class: "Hunter",
          img: require("./assets/" + "Hunter.png")
        },

        {
          class: "Mage",
          img: require("./assets/" + "Mage.png")
        },

        {
          class: "Paladin",
          img: require("./assets/" + "Paladin.png")
        },

        {
          class: "Priest",
          img: require("./assets/" + "Priest.png")
        },

        {
          class: "Rogue",
          img: require("./assets/" + "Rogue.png")
        },

        {
          class: "Shaman",
          img: require("./assets/" + "Shaman.png")
        },

        {
          class: "Warlock",
          img: require("./assets/" + "Warlock.png")
        },

        {
          class: "Warrior",
          img: require("./assets/" + "Warrior.png")
        },

        {
          class: "Neutral",
          img: require("./assets/" + "Neutral.png")
        },

      ],

      ALL_CLASSES: [
        "Druid",
        "Mage",
        "Paladin",
        "Priest",
        "Rogue",
        "Shaman",
        "Warlock",
        "Warrior",
        "Hunter",
        "Neutral",
      ],

      CARD_LOADER_TEXT_HEIGHT: 25,

      HEARTHSTONE_CARD_SEGMENTS: [
        "Basic",
        "The Witchwood",
        "The Boomsday Project",
        "Rastakhan's Rumble",
        "Rise of Shadows"
      ],

      cards:  [{}, {}, {}, {}, {}, {}, {}, {}],

      heroSelected: "None",

      cardClassFilter: [
        "Druid",
        "Mage",
        "Paladin",
        "Priest",
        "Rogue",
        "Shaman",
        "Warlock",
        "Warrior",
        "Hunter",
        "Neutral",
      ],

      cardExpansionFilter: [
        "Basic",
        "The Witchwood",
        "The Boomsday Project",
        "Rastakhan's Rumble",
        "Rise of Shadows"
      ],
      
      // Index of viewing for cardViewFiltered view
      cardViewIndex: 0,
      
      // Max view (depends on size of the cardView array)
      cardViewIndexMax: 64,

      viewingLastPage: false,

      // Dynamic collection of cards for viewing
      cardViewFiltered: [],

      // Database/cache of all cards after they are fetched from server
      cardDatabase: {
        /*
          "0" : {
          // IMPORT CARDS
          },
          "1" : {
          // IMPORT CARDS
          }
        */
      }

    }

  },

  methods: {

    setClassFilter(selectedClass) {

      // From viewing all/(1 other) to viewing just the selected class
      if(this.cardClassFilter.indexOf(selectedClass) != -1 && this.cardClassFilter.length > 1 ||
         this.cardClassFilter.indexOf(selectedClass) == -1 && this.cardClassFilter.length == 1) {
        this.cardClassFilter = [selectedClass]
      }

      // From viewing just selectedClass class back to ALL CLASSES (filter removed)
      else if(this.cardClassFilter.indexOf(selectedClass) != -1 && this.cardClassFilter.length == 1) {
        this.cardClassFilter = this.ALL_CLASSES
      }

      this.setView(0)
    },

    toggleExpansionFilter(selectedExpansion) {

      // From viewing all/(1 other) to viewing just the selected class
      if(this.cardExpansionFilter.indexOf(selectedExpansion) != -1 ) {
        this.cardExpansionFilter.splice( this.cardExpansionFilter.indexOf(selectedExpansion), 1 )
      }

      else {
        this.cardExpansionFilter.push(selectedExpansion)
      }

      this.setView(0)
    },

    async selectCost(cost) {

      if(this.asyncDataInTransit) {
        return false
      }
      
      this.viewingCost = cost

      // Display loading text
      this.setCardLoaderHeight(this.CARD_LOADER_TEXT_HEIGHT, `Loading card(${cost}) data...`)

      this.asyncDataInTransit = true

      // Gets the cards by card-cost cost
      const response = await this.getCardsByCost(this.viewingCost)

      this.asyncDataInTransit = false
      
      // Once that request returns, then populate the cards to screen
      if (response) {
        cl("Database load(1) successful! ", this.cardDatabase)
        this.setView(0)
        this.setCardLoaderHeight(0, "")
      }

      else {
        cl("Card database load failed: ")
        cl(response)
        this.setCardLoaderHeight(this.CARD_LOADER_TEXT_HEIGHT, "Card load failed.")
      }

    },

    setCardLoaderHeight(divHeight, headerMessage) {

      if(headerMessage != null) {
        // Loading card data...
        this.cardLoaderText = `<p style='color: red; text-align: center; margin-bottom: 20px; '>${headerMessage}</p>`
      }

      this.$refs.cardLoaderTextDiv.style.height = divHeight + "px"

    },

    cycleForward() {
      if (this.cardViewIndex < this.cardViewIndexMax) {

        this.cardViewIndex += 8
        this.setView(this.cardViewIndex)

        if(this.cardViewIndex >= this.cardViewIndexMax) {
          this.viewingLastPage = true
        }

      }
    },

    cycleBack() {
      
      if (this.cardViewIndex > 0) {

        this.cardViewIndex -= 8
        this.setView(this.cardViewIndex)

        if(this.cardViewIndex < this.cardViewIndexMax) {
          this.viewingLastPage = false
        }

      }

    },

    async getCardsSevenAndUp() {

      for(let _cardCost in [7, 8, 9, 10]) {
      
        // If this set of cards has not already been loaded
        if (this.cardDatabase[_cardCost] == null) {

          // HTTP Request header and GET variables
          let httpRequestObject = {

            headers: {
              "X-Mashape-Key": this.apiKey
            },

            params: {
              cost: _cardCost
            }

          }
        
          // Make the HTTP request and deal with response
          const response = await this.$http.get(this.apiBase, httpRequestObject) 
          
          if (response) {

            // Set response data
            let givenData = response.data

            if (givenData) {

              // Create COST object
              let newCostObject = {}

              // Loop through STANDARD card sets and add cards to an object
              this.HEARTHSTONE_CARD_SEGMENTS.forEach(segment => {

                if (givenData[segment]) {
                  newCostObject[segment] = givenData[segment]
                }

              }) 

              // Add cards to card database
              this.cardDatabase[_cardCost] = newCostObject

              return true

            } else {
              cl("No data received.")
              return false
            }

          }

        }

        // Database cards already fetched, use cache
        else {
          return true
        }

      }

    },

    // Get image of a cards based on card cost
    async getCardsByCost(cardCost) {

      // If this set of cards has not already been loaded
      if (this.cardDatabase[cardCost] == null) {

        // HTTP Request header and GET variables
        let httpRequestObject = {

          headers: {
            "X-Mashape-Key": this.apiKey
          },

          params: {
            cost: cardCost
          }

        }
      
        // Make the HTTP request and deal with response
        const response = await this.$http.get(this.apiBase, httpRequestObject) 
        
        if (response) {

          // Set response data
          let givenData = response.data
          cl(response.data)

          if (givenData) {

            // Create COST object
            let newCostObject = {}

            // Loop through STANDARD card sets and add cards to an object
            this.HEARTHSTONE_CARD_SEGMENTS.forEach(segment => {

              if (givenData[segment]) {
                newCostObject[segment] = givenData[segment]
              }

            }) 

            // Add cards to card database
            this.cardDatabase[cardCost] = newCostObject

            return true

          } else {
            cl("No data received.")
            return false
          }

        }

      }

      // Database cards already fetched, use cache
      else {
        return true
      }

    },

    // Gets cards into a flat viewing database
    organizeCards() {

      this.cardViewIndex = 0
      this.cardViewFiltered = []
      
      // Populate cardViewFiltered
      this.HEARTHSTONE_CARD_SEGMENTS.forEach(segment => {

        // Selected group of card object
        let viewObject = this.cardDatabase[this.viewingCost][segment]

        if (viewObject) {

          viewObject.forEach(item => {
            
            // Add the card to the viewable list if the class and expansion is not filtered out
            if(this.cardClassFilter.indexOf(item.playerClass) != -1 && this.cardExpansionFilter.indexOf(segment) != -1) {

              this.cardViewFiltered.push(item)

            }

          })

        } else {
          cl("ERROR: viewObject is NULL (around line 174")
        }

      })

      // Set max card view
      this.cardViewIndexMax = this.cardViewFiltered.length - 9

    },
    
    // Display 8 cards (will eventually be based on a filter)
    setView(index) {

      if(this.asyncDataInTransit) { 
        return false
      }

      // Move cards into a flattened array called cardViewFiltered
      this.organizeCards()

      // Trigger children nodes to update ERROR images to SUCCESS
      this.updatePage += 1;

      this.cardViewIndex = index
      this.cards = [];
      
      if(this.cardViewFiltered.length > 0) {
        for (let i = index; i < index + 8; i++) {

          let chosenCard = this.cardViewFiltered[i]

          if(chosenCard != null) {
            this.cards.push( this.cardViewFiltered[i] )
          }

          else {
            this.cards.push({
              name: ""
            })
          }
        }
      }

    },
    
    // Loads one-cost cards on load
    async init() {
      
      // Display loading text
      this.setCardLoaderHeight(this.CARD_LOADER_TEXT_HEIGHT)

      this.asyncDataInTransit = true

      // Gets the cards by card-cost 1
      const response = await this.getCardsByCost(this.viewingCost)

      this.asyncDataInTransit = false
      
      // Once that request returns, then populate the cards to screen
      if (response) {
        cl("Database load(1) successful! ", this.cardDatabase)
        this.setView(0)
        this.cardLoaderText = "";
        this.setCardLoaderHeight(0)
      }

      else {
        cl("Card database load failed: ")
        cl(response)
        this.cardLoaderText = "Card load failed.";
      }


    }

  },

}
</script>

<style>

  * {
    margin: 0;
    padding: 0;
  }
  
  @font-face {
    font-family: "Baker";
    src: url("assets/fonts/baker-denmark-one.otf");
  }

  body {
    background: rgb(255, 205, 130);
    background: linear-gradient(rgb(255, 205, 130) 0%, rgb(255, 205, 130) 80%, rgb(216, 173, 110) 100%);
    font-family: "Baker", "Arial";
  }

  .classes-wrapper {
    width: 960px;
    height: 150px;
    margin: 0 auto;
  }

  .classes-grid {
    display: inline-grid;
    width: 100%;
    height: inherit;

    grid-template-rows: auto;
    grid-template-columns: auto auto auto auto auto auto auto auto auto auto ;
  }

  .classes-wrapper h1 {
    font-size: 1em;
    text-align: center;

    position: relative;

    left: -5px;

    padding: 0;
    margin: 0;
  }

  .my-class {
    width: auto;
    height: auto;
    background: none;

    opacity: 0.5;

    cursor: pointer;

    transition: opacity 0.9s, background 0.7s;
  }
  .my-class:hover {
    opacity: 0.7;
  }

  .active-class {
    opacity: 1.0;
  }

  .my-class img {
    width: auto;
    height: 136px;
  }

  /* Header */

  .header {
    width: 100%;
    height: 60px;

    padding-bottom: 20px;
  }

  #card-loader-text {
    height: 1px;

    transition: height 1s;
  }

  .logo-wrapper {
    width: 400px;
    margin: 0 auto;
  }

  .logo-wrapper img {
    width: 70px;
    float: left;
    height: auto;
    margin: 0 auto;
  }

  .logo-wrapper span {
    display: inline-block;
    margin: 20px 0 0 5px;
    font-size: 30px;
    font-weight: bold;
    letter-spacing: 2px;
    height: 100%;
    vertical-align: center;
    text-shadow: 2px 2px 2px rgba(0,0,0,0.2);
  }

  .header-container{
    margin: 0;
    width: 100%;
    height: 40px;
    clear: both;

    position: relative;

    top: 20px;
  }

  .center-container {
    display:flex;
    justify-content: space-around;	
    align-items: center;
    width: 100%;
    height: 700px;

    margin-bottom: 50px;
  }
  
  .travel-buttons-container {
    display:flex;
    justify-content: center;
    align-items: center;
    height:50px;
  }

  .travel-buttons {
    display:flex;
    font-size:40px;
    justify-content: center;
    align-items: center;
    border: 3px groove rgb(255, 153, 0);
    height: 20px;
    width:10px;
    
    padding:0.35em 1.2em;
    margin:0 0.3em 0.3em 0;
    font-weight:300;
    transition: all 0.2s;
    cursor:pointer;

    background: rgb(255, 217, 161);
  }

  .travel-buttons:hover {
    color:#000000;
    background:rgb(254, 255, 191);
  }
  
  /* Cards */

  .card-container {
    display: inline-grid;
    width: auto;
    max-width: 900px;
    min-width: 800px;
    height: inherit;
    margin: 0 auto;
    padding: 10px;

    background: rgb(255, 217, 161);
    background: linear-gradient(rgb(255, 224, 177) 0%, rgb(255, 224, 177) 20%, rgb(255, 217, 161) 40%, rgb(255, 217, 161) 100% );
    border: 4px groove rgb(255, 207, 134);

    /* creates a 4 by 2 css-grid (4 columns, 2 rows) */
    grid-template-columns: 25% 25% 25% 25%;
    grid-template-rows: 50% 50%;
  }

  .card-item {
    width: auto;
    max-width: 100%;
    height: auto;
    max-height: 100%;

  }

  .card-item img {
    display: block;
    width: auto;
    height: 100%;
    margin: 0 auto;
  }

  .card-row-container {
    width: 100%;
    height: 470px;
  }

  .card {
    width: 20%;
    height: 100%;
    max-width: 307px;
    max-height: 465px;
    background: #f00;
    border: 1px solid black;
    float: left;
  }

  .card-img {
    background: yellow;
  }

  /* Card-set filter */

  .expansion-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    
    width: 100%;
    height: 300px;
  }

  .expansion-container h1 {
    width: 960px;
    display: block;
    padding: 10px 0;
    margin-bottom: 10px;

    background: rgb(255, 205, 130);
    background: linear-gradient(rgb(255, 205, 130) 0%, rgb(255, 205, 130) 30%, rgb(255, 228, 187) 100%);

    border: 1px solid none;
    border-bottom: 1px solid rgb(155, 94, 3);
    box-shadow: 0px 3px 3px 0px rgba(0,0,0,0.1);
    border-radius: 0 0 50px 50px;

    text-align: center;
  }

  .expansion {
    width: auto;
    height: 30px;
    margin: 10px auto;
    padding: 4px 15px;

    font-size: 1.4em;

    background: rgb(253, 210, 146);
    box-shadow: 3px 3px 1px 2px rgba(0,0,0,0.3);

    border-radius: 10px 10px 0 0;
  }

  .expansion:nth-child(even) {
    background: rgb(253, 202, 126);
  }

  .expansion input {
    width: 17px;
    height: 17px;
    margin-right: 5px;
  }

  /* Footer */

  .footer-wrapper {
    width: 100%;
    height: 50px;
    padding-top: 70px;
    font-size: 0.6em;
    text-align: center;
    color: rgb(189, 121, 21);

    font-family: "Arial";
  }

  .footer-wrapper a, .footer-wrapper a:visited {
    color: rgb(226, 148, 32);
  }

  .footer-wrapper a:hover {
    opacity: 0.7;
  }

</style>
 